[build]
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
# rustflags = ["-C", "target-feature=+crt-static"]
rustflags = ["-C", "link-arg=-Wl,-undefined,dynamic_lookup"]
linker = "musl-gcc"