// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use serde::Serialize;
use serde::Deserialize;
use crate::model::diesel::alt::alt_schema::*;

#[derive(Insertable,Queryable,QueryableByName,Debug,Serialize,Deserialize,Default,Clone)]
#[diesel(table_name = alt_tag)]
pub struct AltTag {
    pub id: i64,
    pub name: String,
    pub created_time: i64,
    pub updated_time: i64,
}

